name: Branch name
on: 
  push

jobs:
  run-script: 
    runs-on: ubuntu-latest
    env: 
      Branch: GITHUB_REF_NAME
    steps:
      - name: checkout
        uses: actions/checkout@3
      - name: echo branch name
        id: branch
        run: 
          echo "Current branch name is $Branch"
      - name: console branch name
        if: ${{ env.Branch == 'main' }}
        run: |
          node script.js ${{ env.Branch }}
