name: Branch name
on: 
  push

env: 
  Branch: ${{ github.REF_NAME }}

jobs:
  echo-branch-name: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: display branch name
        id: branch
        run: |
          echo "Current branch name is ${{ env.Branch }}"
  console-branch-name:
    if: ${{ github.REF_NAME == 'main' }}
    runs-on: ubuntu-latest
    needs: echo-branch-name
    steps:
      - run:
          cd .. node script.js ${{ env.Branch }}
  