name: Branch name
on: 
  push

jobs:
  display-branch-name: 
    runs-on: ubuntu-latest
    env: 
      Branch: ${{ github.ref }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: echo branch name
        id: branch
        run: 
          echo "Current branch name is ${{ env.Branch }}"
      - name: console branch name
        if: ${{ env.Branch == 'refs/heads/main' }}
        run: |
          node script.js ${{ env.Branch }}
